"""The logo files the EXE is built with.

``build/ofis.spec`` and ``build/installer.iss`` point straight at
``resources/icons/ofis.ico``, and the running app loads ``ofis_256.png``. All
three are generated by ``scripts/make_icon.py`` and committed, so nothing here
can be caught at build time — it is caught here instead.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
ICONS = ROOT / "resources" / "icons"

#: What the Windows shell asks for: the taskbar, Alt-Tab, the desktop, and the
#: file properties dialog each pick a different one. A missing size is not an
#: error — Windows scales the nearest, badly.
WANTED = {(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)}


def test_the_ico_carries_every_size_windows_asks_for() -> None:
    with Image.open(ICONS / "ofis.ico") as ico:
        assert set(ico.info["sizes"]) >= WANTED


@pytest.mark.parametrize("name", ["ofis_256.png", "ofis_logo.png",
                                  "ofis_logo_dark.png"])
def test_the_logo_files_are_there_and_have_transparency(name: str) -> None:
    with Image.open(ICONS / name) as img:
        assert img.mode == "RGBA", f"{name} lost its alpha channel"
        assert img.width >= 256 and img.height >= 256


def test_the_window_icon_is_square_at_the_size_the_app_loads() -> None:
    """``src/app.py`` hands this straight to ``QIcon`` for every window."""
    with Image.open(ICONS / "ofis_256.png") as img:
        assert img.size == (256, 256)


def test_the_lockup_is_wide_and_not_cropped_tight() -> None:
    """The wordmark sits beside the mark, with clear space around the whole.

    A logo trimmed flush to its glyphs reads as a mistake wherever it is
    pasted, so the generator gives the clear space back after trimming.
    """
    with Image.open(ICONS / "ofis_logo.png") as img:
        assert img.width > img.height * 2, "the wordmark is missing"
        box = img.getbbox()
        assert box[0] > 0 and box[1] > 0, "artwork runs into the left/top edge"
        assert box[2] < img.width and box[3] < img.height


def test_the_generator_still_reproduces_the_committed_icon() -> None:
    """Regenerating must give back exactly what is committed.

    Otherwise the design in the script and the file the EXE ships drift apart,
    and the next person to run the script silently changes the app's icon.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "_make_icon", ROOT / "scripts" / "make_icon.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    fresh = module.build_icon().resize((256, 256), Image.LANCZOS)
    with Image.open(ICONS / "ofis_256.png") as committed:
        assert fresh.tobytes() == committed.convert("RGBA").tobytes(), (
            "resources/icons/ofis_256.png no longer matches "
            "scripts/make_icon.py — rerun the script and commit the result")
